### ISSUE TITLE
Make lights stay on for 1 or 1.5 seconds after tap-off

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/lens-reader#36]
- [ ] LEDs stay on for 1 or 1.5 seconds after tap-off of a lens.
- [ ] The time should be an environment variable `LENS_HOLD_TIME_SECS` that defaults to 1.5.

**Comment by framigni** [comment]
@luciepaterson @pippshea 
we'd like feedback from you about this, from a UX point of view, thanks
