### ISSUE TITLE
Update Lens Reader LED responses to flash for 2 seconds

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/lens-reader#64]
- [x] Failed Lens tap - make the LEDs flash purple for 2 seconds (~3 times)
- [x] Success Lens tap - make the LEDs fade blue
- [x] Make both of these happen even if the Lens is held on the reader

See: https://trello.com/c/MIevjVOQ/136-change-failed-lens-error-lights-on-lens-readers-to-be-flashing-for-2-seconds

**Comment by sebchan** [comment]
@sighmon i think we should NOT have the blue success flash twice. Just make it glow. Then the distinction between the two states is clearer

**Comment by sighmon** [comment]
@sebchan Ah yes, good plan. I'll implement that.
